#!/usr/bin/env python3
"""Compare compiled dbt SQL to toDbtSql without Jinja; parse Spark SQL with sqlglot."""
from __future__ import annotations

import pathlib
import re
import sys

import sqlglot
from sqlglot import exp

FIVE = ["rename_simples", "expr_cast", "left_join", "where_filter", "group_agg"]


def strip_jinja(sql: str) -> str:
    sql = re.sub(
        r"^-- @generated by Strata[^\n]*\n",
        "",
        sql,
    )
    sql = re.sub(r"\{\{\s*ref\('([^']+)'\)\s*\}\}", r"\1", sql)
    sql = re.sub(r"\{\{\s*source\('([^']+)',\s*'([^']+)'\)\s*\}\}", r"\2", sql)
    return sql.strip() + "\n"


def strip_compiled_header(sql: str) -> str:
    lines = [ln for ln in sql.splitlines() if not ln.startswith("--")]
    return "\n".join(lines).strip() + "\n"


def qualify_tables(sql: str, read: str) -> str:
    ast = sqlglot.parse_one(sql, read=read)
    for table in ast.find_all(exp.Table):
        table.set("catalog", None)
        table.set("db", None)
        ident = table.this
        if ident is not None:
            name = ident.name if hasattr(ident, "name") else str(ident)
            short = name.split(".")[-1].strip('"')
            table.set("this", exp.to_identifier(short))
    return ast.sql(dialect="duckdb", normalize=True, pretty=True)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: compare-transform.py <compiled-dir> <emitted-dir>", file=sys.stderr)
        return 2
    compiled_dir = pathlib.Path(sys.argv[1])
    emitted_dir = pathlib.Path(sys.argv[2])
    for name in FIVE:
        generated = (emitted_dir / f"{name}.dbt.sql").read_text()
        compiled = (compiled_dir / f"{name}.sql").read_text()
        left = qualify_tables(strip_jinja(generated), "duckdb")
        right = qualify_tables(strip_compiled_header(compiled), "duckdb")
        if left != right:
            print(f"FAIL {name}: compiled ≢ toDbtSql without Jinja", file=sys.stderr)
            print("--- toDbtSql/sqlglot ---", file=sys.stderr)
            print(left, file=sys.stderr)
            print("--- compiled/sqlglot ---", file=sys.stderr)
            print(right, file=sys.stderr)
            return 1
        spark = (emitted_dir / f"{name}.sql").read_text()
        sqlglot.parse_one(spark, read="spark")
        print(f"ok {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
