import { nodeSel, selectCanvasDetailLevel } from "./canvas-support";

const DBT_DEMO = "dbt-demo";
const PEDIDO = "silver.stg_pedido";
const CLIENTE = "silver.stg_cliente";
const MANUAL = "reporting.daily_views";
const NEW_MODEL = "gold.d4_from_sel";

type DomainRow = { id: string; slug: string };
type ProjectRow = { id: string; slug: string };

function visitVendas(): void {
  cy.request("GET", "/api/domains").then((res) => {
    const body = res.body as { domains: DomainRow[] };
    const domain = body.domains.find((d) => d.slug === DBT_DEMO);
    if (!domain) throw new Error(`domain ${DBT_DEMO} not found`);
    cy.request("POST", `/api/domains/${domain.id}/activate`).then(() => {
      cy.request("GET", "/api/projects").then((pres) => {
        const projects = pres.body as { projects: ProjectRow[] };
        const proj = projects.projects.find((p) => p.slug === "vendas");
        if (!proj) throw new Error("project vendas not found");
        cy.request("POST", `/api/projects/${proj.id}/activate`).then(() => {
          cy.request("GET", "/api/project").its("body.format").should("eq", "dbt");
          cy.visit("/");
          cy.get(`[data-testid="rf__node-${PEDIDO}"]`, { timeout: 20000 }).should("exist");
        });
      });
    });
  });
}

function dbtFiles(): Cypress.Chainable<Record<string, string>> {
  return cy.request("GET", "/api/project").then((res) => {
    expect(res.body.format).to.eq("dbt");
    return res.body.files as Record<string, string>;
  });
}

function waitPut(): void {
  cy.wait("@dbtPut");
}

function e2eDataDir(): string {
  const fromEnv = Cypress.env("E2E_DATA_DIR");
  return typeof fromEnv === "string" && fromEnv.length > 0 ? fromEnv : ".e2e-data";
}

function restoreDbtDemo(): void {
  const root = e2eDataDir();
  cy.exec(
    `rm -rf "${root}/domains/dbt-demo" && mkdir -p "${root}/domains" && cp -R cypress/fixtures/data/domains/dbt-demo "${root}/domains/dbt-demo"`,
  );
}

function createFromSelection(): void {
  cy.window().then((win) => {
    cy.stub(win, "prompt").returns(NEW_MODEL);
  });
  cy.get('[data-testid="schema-tree"] button[aria-label="' + PEDIDO + '"]').click({ force: true });
  cy.get('[data-testid="schema-tree"] button[aria-label="' + CLIENTE + '"]').click({
    force: true,
    altKey: true,
  });
  cy.get('[data-testid="inspector-multi"]').should("be.visible");
  cy.get('[data-testid="inspector-new-model-from-selection"]').click();
  waitPut();
  cy.get(`[data-testid="rf__node-${NEW_MODEL}"]`, { timeout: 20000 }).should("exist");
}

describe("D4 transform", () => {
  beforeEach(() => {
    restoreDbtDemo();
    cy.intercept("PUT", "**/api/projects/*").as("dbtPut");
    visitVendas();
  });

  afterEach(() => {
    cy.request("GET", "/api/domains").then((res) => {
      const body = res.body as { domains: DomainRow[] };
      const domain = body.domains.find((d) => d.slug === "local");
      if (!domain) throw new Error("domain local not found");
      cy.request("POST", `/api/domains/${domain.id}/activate`);
    });
  });

  it("G7: Novo model a partir da seleção writes transform YAML + .sql", () => {
    createFromSelection();
    dbtFiles().then((files) => {
      const yml = files["models/vendas/gold/_d4_from_sel.yml"];
      expect(yml, "managed yaml").to.contain("name: d4_from_sel");
      expect(yml).to.contain("transform:");
      expect(yml).to.match(/from:/);
      expect(yml).to.match(/alias:\s*a/);
      expect(yml).to.contain("joins:");
      expect(yml).to.match(/on:/);
      const sql = files["models/vendas/gold/d4_from_sel.sql"];
      expect(sql, "generated sql").to.contain("@generated by Strata");
      expect(sql).to.match(/ref\(|source\(/);
    });
  });

  it("G8: expr in inspector regenerates .sql with the expression", () => {
    createFromSelection();
    cy.get(nodeSel(NEW_MODEL)).click("top", { force: true });
    cy.get('[data-testid="inspector-section-transform"]').click();
    cy.get('[data-testid="inspector-transform-expr-id"]')
      .clear()
      .type("cast(a.id as bigint){enter}");
    waitPut();
    dbtFiles().then((files) => {
      expect(files["models/vendas/gold/d4_from_sel.sql"]).to.contain("cast(a.id as bigint)");
    });
  });

  it("G9: Exportar Spark SQL writes output/spark/…", () => {
    createFromSelection();
    cy.get(nodeSel(NEW_MODEL)).click("top", { force: true });
    cy.get('[data-testid="inspector-section-transform"]').click();
    cy.intercept("POST", "**/api/export/spark-sql").as("sparkSql");
    cy.get('[data-testid="export-spark-sql"]').click();
    cy.wait("@sparkSql").then((interception) => {
      const body = interception.response?.body as { files?: string[] };
      expect(body.files?.some((f) => f.includes("output/spark"))).to.eq(true);
    });
    cy.get('[data-testid="export-spark-sql-result"]').should("contain", "output/spark");
  });

  it("G10: manual model has no Transformação; editing columns does not rewrite .sql", () => {
    cy.get(nodeSel(MANUAL)).click("top", { force: true });
    cy.get('[data-testid="inspector-section-transform"]').should("not.exist");
    dbtFiles().then((before) => {
      const sqlPath = "models/vendas/gold/daily_views.sql";
      const sqlBefore = before[sqlPath];
      selectCanvasDetailLevel("Colunas");
      cy.get('[data-testid="inspector-section-columns"]').then(($el) => {
        if ($el.attr("data-state") !== "open") {
          cy.wrap($el).click();
        }
      });
      cy.get('[data-testid="inspector-section-columns"]').contains("views").click({ force: true });
      cy.get("#inspector-col-type-views").clear().type("bigint{enter}");
      waitPut();
      dbtFiles().then((after) => {
        expect(after[sqlPath]).to.eq(sqlBefore);
        expect(after["models/vendas/gold/_daily_views.yml"]).to.contain("bigint");
      });
    });
  });
});
