-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.
with p as (
  select * from {{ ref('stg_pedido') }}
)
select
  p.cliente_id as cliente_id,
  sum(p.valor) as total
from p
group by p.cliente_id
