-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.
with p as (
  select * from {{ ref('stg_pedido') }}
),
c as (
  select * from {{ ref('stg_cliente') }}
)
select
  p.id as id,
  c.nome as nome
from p
left join c
  on p.cliente_id = c.id
