import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  contextFromFiles,
  toDbtSql,
  toSparkSql,
  validateTransform,
  type TransformContext,
} from "@/features/dbt-source/transform";
import { MANAGED_SQL_HEADER } from "@/features/dbt-source/managedHeader";
import type { ProjectFiles } from "@/features/dbt-source";

const STG_PEDIDO = {
  name: "stg_pedido",
  schema: "silver",
  columns: [{ name: "id" }, { name: "cliente_id" }, { name: "valor" }, { name: "status" }],
};

const STG_CLIENTE = {
  name: "stg_cliente",
  schema: "silver",
  columns: [{ name: "id" }, { name: "nome" }],
};

function ctx(model: TransformContext["models"][number]): TransformContext {
  return {
    models: [STG_PEDIDO, STG_CLIENTE, model],
    sources: [
      {
        source: "bronze_vendas",
        table: "canais",
        schema: "bronze",
        database: "raw_db",
      },
    ],
    defaultSchema: "analytics",
  };
}

const okModel: TransformContext["models"][number] = {
  name: "ok_model",
  managed: true,
  transform: {
    from: { ref: "stg_pedido", alias: "p" },
    joins: [{ ref: "stg_cliente", alias: "c", type: "left", on: "p.cliente_id = c.id" }],
    where: "p.status <> 'cancelado'",
    group_by: [],
  },
  columns: [
    { name: "id", lineage: [{ from: "p.id" }] },
    { name: "cliente_nome", lineage: [{ from: "c.nome" }] },
  ],
};

describe("D4 G1 validateTransform", () => {
  it("alias inexistente", () => {
    const problems = validateTransform(
      ctx({
        ...okModel,
        name: "bad_alias",
        columns: [{ name: "id", lineage: [{ from: "x.id" }] }],
      }),
      "bad_alias",
    );
    expect(problems.length).toBeGreaterThan(0);
    expect(problems.some((p) => /alias/i.test(p.message))).toBe(true);
  });

  it("várias origens sem expr", () => {
    const problems = validateTransform(
      ctx({
        ...okModel,
        name: "multi_from",
        columns: [
          {
            name: "id",
            lineage: [{ from: "p.id" }, { from: "c.id" }],
          },
        ],
      }),
      "multi_from",
    );
    expect(problems.some((p) => /várias origens|expr/i.test(p.message))).toBe(true);
  });

  it("coluna sem linhagem", () => {
    const problems = validateTransform(
      ctx({
        ...okModel,
        name: "no_lin",
        columns: [{ name: "id" }, { name: "orphan", lineage: [{ from: "p.id" }] }],
      }),
      "no_lin",
    );
    expect(problems.some((p) => /sem linhagem/i.test(p.message))).toBe(true);
  });

  it("join sem on", () => {
    const problems = validateTransform(
      ctx({
        ...okModel,
        name: "join_on",
        transform: {
          from: { ref: "stg_pedido", alias: "p" },
          joins: [{ ref: "stg_cliente", alias: "c", type: "left" }],
        },
      }),
      "join_on",
    );
    expect(problems.some((p) => /join/i.test(p.message) && /on/i.test(p.message))).toBe(true);
  });

  it("group_by com coluna não agregada sem expr", () => {
    const problems = validateTransform(
      ctx({
        name: "bad_grp",
        managed: true,
        transform: {
          from: { ref: "stg_pedido", alias: "p" },
          group_by: ["p.cliente_id"],
        },
        columns: [
          { name: "cliente_id", lineage: [{ from: "p.cliente_id" }] },
          { name: "valor", lineage: [{ from: "p.valor" }] },
        ],
      }),
      "bad_grp",
    );
    expect(problems.some((p) => /group_by|agreg/i.test(p.message))).toBe(true);
  });

  it("ok", () => {
    expect(validateTransform(ctx(okModel), "ok_model")).toEqual([]);
  });
});

describe("D4 G2 toDbtSql", () => {
  it("rename simples", () => {
    const sql = toDbtSql(
      ctx({
        name: "rename_simples",
        managed: true,
        transform: {
          from: { source: ["bronze_vendas", "canais"], alias: "s0" },
        },
        columns: [{ name: "canal_id", lineage: [{ from: "s0.canal_id" }] }],
      }),
      "rename_simples",
    );
    expect(sql.startsWith(`${MANAGED_SQL_HEADER}\n`)).toBe(true);
    expect(sql).toContain("{{ source('bronze_vendas', 'canais') }}");
    expect(sql).toContain("s0.canal_id as canal_id");
    expect(sql).toContain("with s0 as (");
    expect(sql)
      .toBe(`-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.
with s0 as (
  select * from {{ source('bronze_vendas', 'canais') }}
)
select
  s0.canal_id as canal_id
from s0
`);
  });

  it("expr com cast", () => {
    const sql = toDbtSql(
      ctx({
        name: "expr_cast",
        managed: true,
        transform: { from: { ref: "stg_pedido", alias: "p" } },
        columns: [
          {
            name: "valor",
            lineage: [
              {
                from: "p.valor",
                expr: "cast(p.valor as decimal(12,2))",
              },
            ],
          },
        ],
      }),
      "expr_cast",
    );
    expect(sql)
      .toBe(`-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.
with p as (
  select * from {{ ref('stg_pedido') }}
)
select
  cast(p.valor as decimal(12,2)) as valor
from p
`);
  });

  it("left join", () => {
    const sql = toDbtSql(
      ctx({
        name: "left_join",
        managed: true,
        transform: {
          from: { ref: "stg_pedido", alias: "p" },
          joins: [
            {
              ref: "stg_cliente",
              alias: "c",
              type: "left",
              on: "p.cliente_id = c.id",
            },
          ],
        },
        columns: [
          { name: "id", lineage: [{ from: "p.id" }] },
          { name: "nome", lineage: [{ from: "c.nome" }] },
        ],
      }),
      "left_join",
    );
    expect(sql)
      .toBe(`-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.
with p as (
  select * from {{ ref('stg_pedido') }}
),
c as (
  select * from {{ ref('stg_cliente') }}
)
select
  p.id as id,
  c.nome as nome
from p
left join c
  on p.cliente_id = c.id
`);
  });

  it("where", () => {
    const sql = toDbtSql(
      ctx({
        name: "where_filter",
        managed: true,
        transform: {
          from: { ref: "stg_pedido", alias: "p" },
          where: "p.status <> 'cancelado'",
        },
        columns: [{ name: "id", lineage: [{ from: "p.id" }] }],
      }),
      "where_filter",
    );
    expect(sql)
      .toBe(`-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.
with p as (
  select * from {{ ref('stg_pedido') }}
)
select
  p.id as id
from p
where p.status <> 'cancelado'
`);
  });

  it("group by + agregação", () => {
    const sql = toDbtSql(
      ctx({
        name: "group_agg",
        managed: true,
        transform: {
          from: { ref: "stg_pedido", alias: "p" },
          group_by: ["p.cliente_id"],
        },
        columns: [
          { name: "cliente_id", lineage: [{ from: "p.cliente_id" }] },
          {
            name: "total",
            lineage: [{ from: "p.valor", expr: "sum(p.valor)" }],
          },
        ],
      }),
      "group_agg",
    );
    expect(sql)
      .toBe(`-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.
with p as (
  select * from {{ ref('stg_pedido') }}
)
select
  p.cliente_id as cliente_id,
  sum(p.valor) as total
from p
group by p.cliente_id
`);
  });
});

describe("D4 G3 toSparkSql", () => {
  const sparkOpts = { catalog: "main", schema: "analytics" };

  it("rename simples (source database)", () => {
    const sql = toSparkSql(
      ctx({
        name: "rename_simples",
        managed: true,
        transform: {
          from: { source: ["bronze_vendas", "canais"], alias: "s0" },
        },
        columns: [{ name: "canal_id", lineage: [{ from: "s0.canal_id" }] }],
      }),
      "rename_simples",
      sparkOpts,
    );
    expect(sql).not.toContain("{{");
    expect(sql).not.toMatch(/\bwith\b/i);
    expect(sql).toBe(`select
  s0.canal_id as canal_id
from main.raw_db.bronze.canais as s0
`);
  });

  it("expr com cast", () => {
    const sql = toSparkSql(
      ctx({
        name: "expr_cast",
        managed: true,
        transform: { from: { ref: "stg_pedido", alias: "p" } },
        columns: [
          {
            name: "valor",
            lineage: [{ from: "p.valor", expr: "cast(p.valor as decimal(12,2))" }],
          },
        ],
      }),
      "expr_cast",
      sparkOpts,
    );
    expect(sql).toBe(`select
  cast(p.valor as decimal(12,2)) as valor
from main.silver.stg_pedido as p
`);
  });

  it("left join", () => {
    const sql = toSparkSql(
      ctx({
        name: "left_join",
        managed: true,
        transform: {
          from: { ref: "stg_pedido", alias: "p" },
          joins: [
            {
              ref: "stg_cliente",
              alias: "c",
              type: "left",
              on: "p.cliente_id = c.id",
            },
          ],
        },
        columns: [
          { name: "id", lineage: [{ from: "p.id" }] },
          { name: "nome", lineage: [{ from: "c.nome" }] },
        ],
      }),
      "left_join",
      sparkOpts,
    );
    expect(sql).toBe(`select
  p.id as id,
  c.nome as nome
from main.silver.stg_pedido as p
left join main.silver.stg_cliente as c
  on p.cliente_id = c.id
`);
  });

  it("where + config.alias", () => {
    const sql = toSparkSql(
      {
        models: [
          { ...STG_PEDIDO, alias: "pedidos_src" },
          STG_CLIENTE,
          {
            name: "where_filter",
            managed: true,
            transform: {
              from: { ref: "stg_pedido", alias: "p" },
              where: "p.status <> 'cancelado'",
            },
            columns: [{ name: "id", lineage: [{ from: "p.id" }] }],
          },
        ],
        sources: [],
        defaultSchema: "analytics",
      },
      "where_filter",
      sparkOpts,
    );
    expect(sql).toBe(`select
  p.id as id
from main.silver.pedidos_src as p
where p.status <> 'cancelado'
`);
  });

  it("group by + agregação", () => {
    const sql = toSparkSql(
      ctx({
        name: "group_agg",
        managed: true,
        transform: {
          from: { ref: "stg_pedido", alias: "p" },
          group_by: ["p.cliente_id"],
        },
        columns: [
          { name: "cliente_id", lineage: [{ from: "p.cliente_id" }] },
          { name: "total", lineage: [{ from: "p.valor", expr: "sum(p.valor)" }] },
        ],
      }),
      "group_agg",
      sparkOpts,
    );
    expect(sql).toBe(`select
  p.cliente_id as cliente_id,
  sum(p.valor) as total
from main.silver.stg_pedido as p
group by p.cliente_id
`);
  });
});

describe("D4 transform fixture SQL matches toDbtSql", () => {
  it("contextFromFiles of fixtures/dbt-source/transform matches committed .sql", () => {
    const dir = path.dirname(fileURLToPath(import.meta.url));
    const root = path.resolve(dir, "../../../../");
    const fixture = path.join(root, "fixtures/dbt-source/transform");
    const files: ProjectFiles = {};
    const walk = (current: string) => {
      for (const name of readdirSync(current)) {
        const full = path.join(current, name);
        if (statSync(full).isDirectory()) walk(full);
        else
          files[path.relative(fixture, full).split(path.sep).join("/")] = readFileSync(
            full,
            "utf8",
          );
      }
    };
    walk(fixture);
    const context = contextFromFiles(files, "demo");
    for (const name of [
      "rename_simples",
      "expr_cast",
      "left_join",
      "where_filter",
      "group_agg",
    ] as const) {
      expect(toDbtSql(context, name)).toBe(files[`models/demo/gold/${name}.sql`]);
    }
  });
});
