/** First line of a Strata-managed model .sql. D4 generates SQL; D5 owns this string. */
export const MANAGED_SQL_HEADER =
  "-- @generated by Strata — edite pelo canvas; edições manuais tornam este model manual.";
